// <auto-generated />
using DellinDictionary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DellinDictionary.Migrations
{
    [DbContext(typeof(DellinDictionaryDbContext))]
    partial class DellinDictionaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DellinDictionary.Models.Entities.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressApartment")
                        .HasColumnType("integer");

                    b.Property<string>("AddressCity")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AddressHouseNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AddressRegion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("CityCode")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Type")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Uuid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkTime")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AddressCity");

                    b.HasIndex("CityCode");

                    b.HasIndex("AddressCity", "AddressRegion");

                    b.ToTable("offices", (string)null);
                });

            modelBuilder.Entity("DellinDictionary.Models.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Additional")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId")
                        .IsUnique();

                    b.ToTable("phones", (string)null);
                });

            modelBuilder.Entity("DellinDictionary.Models.Entities.Office", b =>
                {
                    b.OwnsOne("DellinDictionary.Models.Entities.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("OfficeId")
                                .HasColumnType("integer");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("OfficeId");

                            b1.ToTable("offices");

                            b1.WithOwner()
                                .HasForeignKey("OfficeId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("DellinDictionary.Models.Entities.Phone", b =>
                {
                    b.HasOne("DellinDictionary.Models.Entities.Office", "Office")
                        .WithOne("Phones")
                        .HasForeignKey("DellinDictionary.Models.Entities.Phone", "OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("DellinDictionary.Models.Entities.Office", b =>
                {
                    b.Navigation("Phones")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
